In [ ]:
import numpy as np
import pandas as pd
import pickle
from sklearn.externals import joblib
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
fin_dt = drive.CreateFile({'id':'1DJz0dEcz85wP_g1frkri1NK0ewEjnY1z'}) # replace the id with id of file you want to access
fin_dt.GetContentFile('final_tran_dt.pkl') 

In [ ]:
fin_df=joblib.load("final_tran_dt.pkl")

In [ ]:
from sklearn.model_selection import train_test_split
from random import randint
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
x=fin_df.drop('subscribed_le',axis=1)
y=fin_df['subscribed_le']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=100)

In [ ]:
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.25, random_state=100) # 0.25 x 0.8 = 0.2

In [ ]:
lr = LogisticRegression(random_state=123)

In [ ]:
lr.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
lr_pred=lr.predict(x_val)

In [ ]:
print(confusion_matrix(y_val,lr_pred))

[[5447  137]
 [ 566  180]]


In [ ]:
print(classification_report(y_val,lr_pred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94      5584
           1       0.57      0.24      0.34       746

    accuracy                           0.89      6330
   macro avg       0.74      0.61      0.64      6330
weighted avg       0.87      0.89      0.87      6330



In [ ]:
gnb = GaussianNB()

In [ ]:
gnb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
gnb_pred=gnb.predict(x_val)

In [ ]:
print(confusion_matrix(y_val,gnb_pred))

[[4895  689]
 [ 330  416]]


In [ ]:
print(classification_report(y_val,gnb_pred))

              precision    recall  f1-score   support

           0       0.94      0.88      0.91      5584
           1       0.38      0.56      0.45       746

    accuracy                           0.84      6330
   macro avg       0.66      0.72      0.68      6330
weighted avg       0.87      0.84      0.85      6330



In [ ]:
neigh = KNeighborsClassifier()

In [ ]:
neigh.fit(x_train_tf,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
knn_pred=neigh.predict(x_val_tf)

In [ ]:
print(confusion_matrix(y_val,knn_pred))

[[5440  144]
 [ 523  223]]


In [ ]:
print(classification_report(y_val,knn_pred))

              precision    recall  f1-score   support

           0       0.91      0.97      0.94      5584
           1       0.61      0.30      0.40       746

    accuracy                           0.89      6330
   macro avg       0.76      0.64      0.67      6330
weighted avg       0.88      0.89      0.88      6330



In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()  
scaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
x_train_tf = scaler.transform(x_train)  
x_test_tf = scaler.transform(x_test) 
x_val_tf = scaler.transform(x_val) 

In [ ]:
svc=SVC()

In [ ]:
svc.fit(x_train_tf,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
svc_pred=svc.predict(x_val_tf)

In [ ]:
print(confusion_matrix(y_val,svc_pred))

[[5481  103]
 [ 536  210]]


In [ ]:
print(classification_report(y_val,svc_pred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94      5584
           1       0.67      0.28      0.40       746

    accuracy                           0.90      6330
   macro avg       0.79      0.63      0.67      6330
weighted avg       0.88      0.90      0.88      6330



In [ ]:
dtrees=DecisionTreeClassifier()

In [ ]:
dtrees.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
dtrees_pred=dtrees.predict(x_val)

In [ ]:
print(confusion_matrix(y_val,dtrees_pred))

[[5221  363]
 [ 347  399]]


In [ ]:
print(classification_report(y_val,dtrees_pred))

              precision    recall  f1-score   support

           0       0.94      0.93      0.94      5584
           1       0.52      0.53      0.53       746

    accuracy                           0.89      6330
   macro avg       0.73      0.73      0.73      6330
weighted avg       0.89      0.89      0.89      6330



In [ ]:
rf=RandomForestClassifier()

In [ ]:
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
rf_pred=rf.predict(x_val)

In [ ]:
print(confusion_matrix(y_val,rf_pred))

[[5406  178]
 [ 384  362]]


In [ ]:
print(classification_report(y_val,rf_pred))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      5584
           1       0.67      0.49      0.56       746

    accuracy                           0.91      6330
   macro avg       0.80      0.73      0.76      6330
weighted avg       0.90      0.91      0.90      6330

